language: node_js
node_js:
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c "CREATE DATABASE invoices_test;" -U postgres